name: PYTHON
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan_job:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - name: Check-out
        uses: actions/checkout@v2
      - name: setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
      - name: install dependencies
        run: |
          python -m pip freeze > requirements.txt
          py -m pip install -r requirements.txt
        
      