name: PYTHON test
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan_job:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Check-out
        uses: actions/checkout@v2
      - name: setup python environment
        uses: actions/setup-python@v2
      - name: install dependencies
        run: |
          python -m pip freeze > requirements.txt
          python -m pip install -r requirements.txt
     